### PR TITLE
min landing pg

### PR DESCRIPTION
**Pull request by parisandmilo**

### CODE REVIEW

**Comment by mbellgb** [comment]
I really like this new index page! I'm not too sure about the alternative background colour though. Do we have a proper secondary colour we could use perhaps? I had a play around and tried using the colour \#90C0D8, which is a little more vibrant. Thoughts? Maybe it doesn't really work for you.



Just an idea, just to get some ideas bouncing around :stuck_out_tongue:

**Comment by parisandmilo** [comment]
Idk about the colour... i don't think it'd be too nice to have it that drastic? It's just a white overlay over the #000033... anyone else? @xoneco @danielgavrilov @techsoc/techsoc-website-dev 

in terms of the hover that makes sense

**Comment by mbellgb** [comment]
Yeah okay, that's a good point. Let's leave it how it is, it fits in better with the rest of the page.

**Comment by parisandmilo** [comment]
@mbellgb alrightie merging ^^

**Pull request merged**
