### PR TITLE
Added orientation page

### PR DESCRIPTION
**Pull request by mbellgb**
As an answer to issue #56, I created this simple page for new members to orient themselves with the many communication channels we now have.

It would be found at the /welcome endpoint. Also, I didn't add a newsletter subscription as I'm not sure how we'll do these yet with the new Ublend system (probably a Google Spreadsheet? Obviously data protection is important etc.)

Let me know what you all think, perhaps there should be an image at the bottom, or a video?

### CODE REVIEW

**Comment by danielgavrilov** [comment]
How will people arrive at this page? Where would it be linked from?

**Comment by mbellgb** [comment]
It would be linked from when someone gets a membership. Do you know if you can display a message when a membership is purchased from the UCLU website? We could have a link there if so

Otherwise, I guess that we can link it manually or just on the UCLU shop page.

**Comment by mbellgb** [comment]
Cheers for adding that correction in @danielgavrilov, good to push to master?

**Comment by danielgavrilov** [comment]
@mbellgb I don't think you can display a message since it's a basket form of checkout where you can have multiple items. 

What do you mean by "link it manually"? And do you mean linking the welcome page as default, rather than the homepage, for UCLU shop?

I'm gonna merge this anyway, it's a good idea to have it, but I don't know how new members could be directed to it.

**Comment by mbellgb** [comment]
Ah right, that's a bit of a shame. And that suggestion could work, I'm not all that aware of how the UCLU system works sadly :disappointed:

**Pull request merged**
